# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aad00bcadcf6e6f41e42d860c6bffed7b1c90a08cb00fcd6e60fbbf0d9383e1d35fb0af4fe0322249c42cf3293647d83e44af04726a3766deee534740743958e

test:
  secret_key_base: 5f12d8174722049baf2a0e1b055e84ad61bd23a84d52214d68d5135d3250272556eaffd00c9aeca6cf22753e0fe3140570fa225a2d28d1af2fc2d2efbfd4a0db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
